config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "wallets#index"

  resources :wallets, except: :show
  resources :withdraw_transactions, only: [:new, :create]
  resources :deposit_transactions, only: [:new, :create]
  resources :transfer_transactions, only: [:new, :create]
  resources :transactions, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < Wallet
end

app/models/team.rb
class Team < Wallet
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :source_wallet, foreign_key: :source, optional: true, class_name: "Wallet"
  belongs_to :target_wallet, foreign_key: :target, optional: true, class_name: "Wallet"

  enum transaction_type: { withdraw: 0, deposit: 1, transfer: 2 }
  enum status: { processing: 0, success: 1, failed: 2 }

  delegate :owner_name, to: :source_wallet, allow_nil: true, prefix: true
  delegate :owner_name, to: :target_wallet, allow_nil: true, prefix: true

  validates :source_wallet, presence: true, if: :source_wallet_required?
  validates :target_wallet, presence: true, if: :target_wallet_required?
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true

  def exec
    Wallet.transaction do
      return success! if source_wallet == target_wallet

      if source_wallet.present?
        source_wallet.assign_attributes(balance: source_wallet.balance - amount)
        source_wallet.save!
      end

      if target_wallet.present?
        target_wallet.assign_attributes(balance: target_wallet.balance + amount)
        target_wallet.save!
      end

      success!
    rescue StandardError => e
      update status: :failed, reason: e.message
    end
  end

  private

  def source_wallet_required?
    !deposit?
  end

  def target_wallet_required?
    !withdraw?
  end
end

app/models/user.rb
class User < Wallet
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  WALLET_TYPES = ["Team", "User", "Stock"]

  has_many :withdraw_transactions, -> { withdraw }, foreign_key: :source, class_name: "Transaction"
  has_many :deposit_transactions, -> { deposit }, foreign_key: :target, class_name: "Transaction"
  has_many :received_transfer_transactions, -> { transfer }, foreign_key: :target, class_name: "Transaction"
  has_many :sent_transfer_transactions, -> { transfer }, foreign_key: :source, class_name: "Transaction"

  validates_presence_of :owner_name, :balance
  validates :balance, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deposit_transactions_controller.rb
class DepositTransactionsController < ApplicationController
  def new
    @transaction = Transaction.deposit.new
  end

  def create
    @transaction = Transaction.deposit.new deposit_params

    if @transaction.save
      flash[:success] = "Transaction is created successfully."
      @transaction.exec

      redirect_to transactions_path
    else
      flash.now[:failed] = "Can not create transaction."
      render :new
    end
  end

  private

  def deposit_params
    params.require(:transaction).permit(
      :target,
      :amount
    )
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end
end

app/controllers/transfer_transactions_controller.rb
class TransferTransactionsController < ApplicationController
  def new
    @transaction = Transaction.transfer.new
  end

  def create
    @transaction = Transaction.transfer.new transfer_params

    if @transaction.save
      flash[:success] = "Transaction is created successfully."
      @transaction.exec

      redirect_to transactions_path
    else
      flash.now[:failed] = "Can not create transaction."
      render :new
    end
  end

  private

  def transfer_params
    params.require(:transaction).permit(
      :target,
      :source,
      :amount
    )
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :load_wallet, only: [:edit, :update, :destroy]

  def index
    @wallets = Wallet.all
  end

  def new
    @wallet = Wallet.new
  end

  def create
    @wallet = Wallet.new wallet_params

    if @wallet.save
      flash[:success] = "Created successfully"

      redirect_to wallets_path
    else
      flash.now[:failed] = "Can not create"

      render :new
    end
  end

  def edit; end

  def update
    if @wallet.update wallet_params
      flash[:success] = "Updated successfully"

      redirect_to wallets_path
    else
      flash.now[:failed] = "Can not update"

      render :edit
    end
  end

  def destroy
    if @wallet.destroy
      flash[:success] = "Destroyed"
    else
      flash[:failed] = "Can not destroy"
    end
    redirect_to wallets_path
  end

  private

  def wallet_params
    params.require(:wallet).permit(:owner_name, :type)
  end

  def load_wallet
    @wallet = Wallet.find(params[:id])
  end
end

app/controllers/withdraw_transactions_controller.rb
class WithdrawTransactionsController < ApplicationController
  def new
    @transaction = Transaction.withdraw.new
  end

  def create
    @transaction = Transaction.withdraw.new withdraw_params

    if @transaction.save
      flash[:success] = "Transaction is created successfully."
      @transaction.exec

      redirect_to transactions_path
    else
      flash.now[:failed] = "Can not create transaction."
      render :new
    end
  end

  private

  def withdraw_params
    params.require(:transaction).permit(
      :source,
      :amount
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deposit_transactions/new.html.slim
h1 Create Transaction
= render "shared/transaction_form", transaction: @transaction, url: deposit_transactions_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title E-Wallet
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body style="width: 800px; margin: auto"
    p
      = link_to "Wallets | ", wallets_path
      = link_to "Transactions | ", transactions_path
      = link_to "Deposit | ", new_deposit_transaction_path
      = link_to "Withdraw | ", new_withdraw_transaction_path
      = link_to "Transfer |", new_transfer_transaction_path
    p
      - flash.each do |type, msg|
        = msg
    = yield

app/views/shared/_transaction_form.html.slim
- wallet_options = Wallet.all.collect {|w| [ "#{w.owner_name}(WalletID: #{w.id})", w.id ] }

= form_for transaction, url: url do |f|
  - transaction.errors.full_messages.each do |msg|
    p style="color: red"
      = msg
  - unless transaction.withdraw?
    p
      = f.label :target, "Target Wallet ID: "
      = f.select("target", wallet_options, { include_blank: true })
  - unless transaction.deposit?
    p
      = f.label :source, "Source Wallet ID: "
      = f.select("source", wallet_options, { include_blank: true })
  p
    = f.label :amount, "Amount: "
    = f.number_field :amount
  p
    = f.submit "Create"

app/views/transactions/index.html.slim
h1 Transaction List
table
  tr
    th Transaction Type
    th Source Wallet
    th Target Wallet
    th Amount
    th Status
    th Reason
  - @transactions.each do |transaction|
    tr
      td
        = transaction.transaction_type
      td
        = transaction.source_wallet_owner_name
      td
        = transaction.target_wallet_owner_name
      td
        = transaction.amount
      td
        = transaction.status
      td
        = transaction.reason

app/views/transfer_transactions/new.html.slim
h1 Create Transaction
= render "shared/transaction_form", transaction: @transaction, url: transfer_transactions_path

app/views/wallets/edit.html.slim
h1 Edit wallet
= form_for @wallet, as: :wallet, url: wallet_path(@wallet), method: :put do |f|
  - @wallet.errors.full_messages.each do |msg|
    p style="color: red"
      = msg
  p
    = f.label :type, "Wallet Type: "
    i
      = @wallet.type
  p
    = f.label :owner_name, "Owner Name: "
    = f.text_field :owner_name

  p
    = f.label :balance, "Balance: "
    i
      = @wallet.balance

  p
    = f.submit "Update"

app/views/wallets/index.html.slim
h1 Wallet List
p
  = link_to "Add new wallet", new_wallet_path
table
  tr
    th Id
    th Owner Name
    th Type
    th Balance
    th Actions
  - @wallets.each do |wallet|
    tr
      td
        = wallet.id
      td
        = wallet.owner_name
      td
        = wallet.type
      td
        = wallet.balance
      td
        = link_to "Edit | ", edit_wallet_path(wallet)
        = link_to "Delete", wallet_path(wallet), method: :delete, data: { confirm: "Are you sure?" }

app/views/wallets/new.html.slim
h1 Add new wallet
- type_options = Wallet::WALLET_TYPES

= form_for @wallet do |f|
  - @wallet.errors.full_messages.each do |msg|
    p style="color: red"
      = msg
  p
    = f.label :type, "Wallet Type: "
    = f.select("type", type_options, { include_blank: true })

  p
    = f.label :owner_name, "Owner Name: "
    = f.text_field :owner_name
  p
    = f.submit "Create"

app/views/withdraw_transactions/new.html.slim
h1 Create Transaction
= render "shared/transaction_form", transaction: @transaction, url: withdraw_transactions_path